### ISSUE TITLE
TypeError: Layout of the output array img is incompatible with cv:

### ISSUE THREAD

**Issue by Ranger-D** [DrMahdiRezaei/DeepSOCIAL#6]
Hello! I'm very interested in your excellent work!
I wanna program the jupyter notebook as a project. After I performed the last step, I got log as below. I wanna know if I installed the mismatch  version of opencv. I installed opencv3.4.4.

_crowdMap, crowdMap = Apply_crowdMap(centroid_dict, image, _crowdMap)
  File "deepsocial.py", line 237, in Apply_crowdMap
TypeError: Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)

**Comment by DrMahdiRezaei** [comment]
Hi, 

We checked our source code with the latest released version of OpenCV and we did not face such an issue. Also, this is the first time that such a problem has been reported after around a year.

We suggest you see the following links: 
https://coderedirect.com/questions/360551/python-opencv-typeerror-layout-of-the-output-array-incompatible-with-cvmat

https://stackoverflow.com/questions/23830618/python-opencv-typeerror-layout-of-the-output-array-incompatible-with-cvmat

https://github.com/clovaai/CRAFT-pytorch/issues/84

You may also add the following code before the line 237 (where the “Apply_crowdMap” is invoked):

image= np.ascontiguousarray(image, dtype=np.uint8)
_crowdMap= np.ascontiguousarray(_crowdMap, dtype=np.uint8)

or alternatively, if the problem comes from the coordinates (the content of “centroid_dict”), you can run the following code before invoking the “Apply_crowdMap” function:

corrected_dict = dict()
for idx, box in centroid_dict.items():
	corrected_dict[idx] = np.array(centroid_dict[idx]).tolist()

and then feed “corrected_dict” into Apply_crowdMap function instead of “centroid_dict”.
